name: build-test-deploy
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: echo "Starting build..."
      - run: npm install
      - run: npm run build 
      - run: echo "Done building!"
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: echo "Starting tests..."
      - run: npm install
      - run: npm test
      - run: echo "Done testing!"
  deploy:
    needs: test
    permissions:
      contents: write
      id-token: write
      pages: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - run: echo "Starting deploy..."
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
      - run: echo "Done deploying!"